import { User, Order, Sentiment, Instruments, Reasons, OptionStrategies } from "@/interfaces/index";

/** Dummy user data. */
export const sampleUserData: User[] = [
  { _id: 101, name: "Alice" },
  { _id: 102, name: "Bob" },
  { _id: 103, name: "Caroline" },
  { _id: 104, name: "Dave" },
];

export const samplePlays: Order[] = [
  {
    _id: 201,
    sentiment: Sentiment.Bullish,
    ticker: "IBUY",
    instrument: Instruments.Stocks,
    isWatching: true,
    entryPrice: 215,
    targetAmount: 0,
    reasoning: Reasons.News,
    exitStrategy: "",
    isShort: false,
    orderAmount: 100,
    riskAmount: 100,
    screenShot: "https://picsum.photos/150/300",
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
  },
  {
    _id: 202,
    sentiment: Sentiment.Bullish,
    ticker: "IDEX",
    instrument: Instruments.Stocks,
    isWatching: true,
    entryPrice: 4.50,
    targetAmount: 7,
    reasoning: Reasons.News,
    exitStrategy: "buy back at 17% drop or anywhere below 2.50",
    isShort: false,
    orderAmount: 100,
    riskAmount: -1,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
  },
  {
    _id: 203,
    sentiment: Sentiment.Bullish,
    ticker: "TSLA",
    instrument: Instruments.Options,
    isWatching: true,
    targetAmount: -1,
    reasoning: Reasons.News,
    exitStrategy: "exit at 60% or 3/10 risk ratio",
    optionsStrategy: OptionStrategies.CREDIT_CALL,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
    entryPrice: 450,
    isShort: false,
    orderAmount: 6,
    riskAmount: 0,
  },
  {
    _id: 204,
    sentiment: Sentiment.Bullish,
    ticker: "ZB",
    instrument: Instruments.Futures,
    isWatching: true,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
    entryPrice: 0,
    isShort: false,
    orderAmount: 0,
    riskAmount: 0,
    targetAmount: -1,
    reasoning: Reasons.News,
  },
  {
    _id: 205,
    sentiment: Sentiment.Bullish,
    ticker: "BTC/USD",
    instrument: Instruments.ForEx,
    isWatching: true,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
    entryPrice: 0,
    isShort: false,
    orderAmount: 0,
    riskAmount: 0,
    reasoning: Reasons.Technicals,
    targetAmount: 3000
  },
  {
    _id: 206,
    sentiment: Sentiment.Bullish,
    ticker: "DOGE",
    instrument: Instruments.Crypto,
    isWatching: true,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
    entryPrice: 0,
    isShort: false,
    orderAmount: 0,
    riskAmount: 0,
    targetAmount: 10,
    reasoning: Reasons.Community
  },
];

export const MoreInformation: { [name: string]: string } = {
  ticker: "",
  sentiment: "",
  instrument: "",
  entryPrice: "",
  targetAmount: "",
  "exit-strategy": "",
  reasoning: "",
  "is-watching": "",
  isShort: "",
  orderAmount: "",
  riskAmount: "",
  screenShot: "",
};