import { User, Order, Sentiment, Instruments, Reasons, OptionStrategies } from "@/interfaces/index";

/** Dummy user data. */
export const sampleUserData: User[] = [
  { id: 101, name: "Alice" },
  { id: 102, name: "Bob" },
  { id: 103, name: "Caroline" },
  { id: 104, name: "Dave" },
];

export const samplePlays: Order[] = [
  {
    id: 201,
    sentiment: Sentiment.Bullish,
    ticker: "IBUY",
    instrument: Instruments.Stocks,
    isWatching: true,
    entryPrice: 300,
    targetAmount: 0,
    reasoning: Reasons.News,
    exitStrategy: "",
    isShort: false,
    orderAmount: 100,
    riskAmount: 100,
    screenShot: "https://picsum.photos/150/300",
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
  },
  {
    id: 202,
    sentiment: Sentiment.Bullish,
    ticker: "IDEX",
    instrument: Instruments.Stocks,
    isWatching: true,
    entryPrice: 400,
    targetAmount: 300,
    reasoning: Reasons.News,
    exitStrategy: "buy back at 17% drop or $332",
    isShort: true,
    orderAmount: 100,
    riskAmount: -1,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
  },
  {
    id: 203,
    sentiment: Sentiment.Bullish,
    ticker: "TSLA",
    instrument: Instruments.Options,
    isWatching: true,
    targetAmount: 0,
    reasoning: Reasons.News,
    exitStrategy: "exit at 60% or 3/10 risk ratio",
    optionsStrategy: OptionStrategies.CREDIT_CALL,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
    entryPrice: 0,
    isShort: false,
    orderAmount: 0,
    riskAmount: 0,
  },
  {
    id: 204,
    sentiment: Sentiment.Bullish,
    ticker: "ZB",
    instrument: "Futuresz",
    isWatching: true,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
    entryPrice: 0,
    isShort: false,
    orderAmount: 0,
    riskAmount: 0,
    targetAmount: 0,
    reasoning: Reasons.News,
  },
  {
    id: 205,
    sentiment: Sentiment.Bullish,
    ticker: "BTC/USD",
    instrument: Instruments.ForEx,
    isWatching: true,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
    entryPrice: 0,
    isShort: false,
    orderAmount: 0,
    riskAmount: 0,
    reasoning: Reasons.Technicals,
    targetAmount: 3000
  },
  {
    id: 206,
    sentiment: Sentiment.Bullish,
    ticker: "DOGE",
    instrument: Instruments.ForEx,
    isWatching: true,
    userName: "234234jalkdjf",
    uid: "234234jalkdjf",
    submitDate: new Date(),
    upVotes: 30,
    downVotes: 3,
    entryPrice: 0,
    isShort: false,
    orderAmount: 0,
    riskAmount: 0,
    targetAmount: 10,
    reasoning: Reasons.Community
  },
];

export const MoreInformation: { [name: string]: string } = {
  ticker: "",
  sentiment: "",
  instrument: "",
  entryPrice: "",
  targetAmount: "",
  "exit-strategy": "",
  reasoning: "",
  "is-watching": "",
  isShort: "",
  orderAmount: "",
  riskAmount: "",
  screenShot: "",
};